/**
 * Convex codegen stub. The real file is generated by `npx convex dev`
 * and overwrites this one with a fully-typed function reference graph.
 *
 * `anyApi` is the untyped placeholder Convex itself ships in their docs
 * for repos that haven't generated yet. Once the founder runs
 * `npx convex dev` the typed `api` and `internal` exports replace it.
 */
import { anyApi } from 'convex/server';

export const api: typeof anyApi = anyApi;
export const internal: typeof anyApi = anyApi;
