/**
 * Convex codegen stub. The real file is generated by `npx convex dev`
 * and overwrites this one with fully-typed bindings against schema.ts.
 *
 * We ship the stub so the repo typechecks before the founder has run
 * `npx convex dev` for the first time. The runtime semantics are
 * identical: typed builders are just generic builders with the data
 * model parameter pre-applied.
 */
import {
  mutationGeneric,
  queryGeneric,
  internalMutationGeneric,
  internalQueryGeneric,
  actionGeneric,
  internalActionGeneric,
} from 'convex/server';

export const query = queryGeneric;
export const mutation = mutationGeneric;
export const action = actionGeneric;
export const internalQuery = internalQueryGeneric;
export const internalMutation = internalMutationGeneric;
export const internalAction = internalActionGeneric;
